djangoapp/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
        path('movies', views.MovieList.as_view(), name='MovieList'),
        path('movies/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
        ]

djangoapp/user/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('', include('django.contrib.auth.urls')),
    path('edit', views.edit, name='edit')

]

djangoapp/core/models.py
from django.db import models



class PersonManager(models.Manager):

    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )

class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director'
        )
        qs = qs.prefetch_related(
            'writers', 'actors'
        )
        return qs

class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
            (NOT_RATED, 'NR - Not Rated'),
            (RATED_G, 'G - General Audiences'),
            (RATED_PG, 'PG - Parental Guidance Suggested'),
            (RATED_R, 'R - Restricted'),
            )

    title = models.CharField(max_length = 140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True)

    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True,
    )

    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank='True'
    )

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title',)
    def __str__(self):
        return '{} {}'.format(self.title, self.year)

class Person(models.Model):

    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    born = models.DateField()
    died = models.DateField(blank=True, null=True)

    objects = PersonManager()

    class Meta:
        ordering = ('first_name', 'last_name')

    def __str__(self):
        if self.died:
            return '{} {} - {} {}'.format(
            self.first_name, self.last_name, self.born, self.died
            )
        return '{} {} - {}'.format(self.first_name, self.last_name, self.born)

class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=120)

    def __str__(self):
        return '{} {} {}'.format(self.movie_id, self.person_id, self.name)

djangoapp/user/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user')
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=50, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def	__str__(self):
        return	'Profilefor user{} '.format(self.user.username)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#       Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#    instance.profile.save()

djangoapp/user/forms.py
from django.contrib.auth.models import User
from django import forms
from user.models import Profile
def validate_unique_user(error_message, **criteria):
    existent_user = User.objects.filter(**criteria)
    if existent_user:
        raise forms.ValidationError(error_message)

class SignupForm(forms.Form):

    username = forms.CharField(max_length=10,widget=forms.TextInput({
        'placdholder': 'User name' }))
    first_name = forms.CharField(max_length=100,widget=forms.TextInput({
         'placdholder': 'First name' }))
    last_name = forms.CharField(max_length=100,widget=forms.TextInput({
        'placdholder': 'Last name' }))
    email = forms.EmailField(widget=forms.EmailInput({
        'placdholder': 'Email', 'placdholder': 'Email' }))
    password = forms.CharField(min_length=6, max_length=20,widget=forms.PasswordInput
              ({'placdholder': 'Password' }))
    repeat_password = forms.CharField(min_length=6, max_length=20,widget=forms.PasswordInput ({'placdholder': 'Repeat password' }))

    def clean_username(self):
        username = self.cleaned_data['username']
        validate_unique_user(error_message='* Username already in use', username=username)
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        validate_unique_user(error_message='* Email already in use', email=email)
        return email

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('repeat_password')
        if password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password1

class UserEditForm(forms.ModelForm):
    class Meta:

        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birth_date', 'photo']

djangoapp/core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from core.models import Movie, Person

class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons()

class MovieList(ListView):
    model = Movie

class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()

djangoapp/user/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render

from user.forms import SignupForm, UserEditForm, ProfileEditForm
from user.models import Profile

@login_required
def dashboard(request):
    return render(request, 'user/dashboard.html', {})

def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username = form.cleaned_data['username'],
                first_name = form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password'],
            )
            user.save()
            # Create profile
            Profile.objects.create(user=user)
            return render(request, 'user/register_done.html', {})
    else:
        form = SignupForm()
    return render(request, 'user/register.html', {'form': form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES,)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfuly')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'user/edit.html', {'user_form': user_form, 'profile_form': profile_form})

djangoapp/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.title }} - {{ block.super }}
{% endblock title %}


{% block main %}

<h1>{{ object }}</h1>
<p class="lead">{{ object.plot }}</p>

{% endblock main %}

{% block sidebar %}
<div >
    <span class="badge badge-primary">{{ object.get_rating_display }}</span>
</div>
{% endblock sidebar %}

djangoapp/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %} 
Movies 
{% endblock title %} 
    
{% block main %}
<ul>
  {% for movie in object_list %}
  <li>
    <a class="" href="{% url 'core:MovieDetail' pk=movie.id %}">
        {{ movie }}
    </a>
  </li>
  {% endfor %}
</ul>


{% if is_paginated %}
<div class="nav">
  <ul class="pagination">
    <li class="page-item">
      <a href="{% url 'core:MovieList' %}?page=1" class="item-link">First</a>
    </li>

    {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}" class="link-item">{{ page_obj.previous_page_number }}</a>
    </li>
    {% endif %}

    <li class="page-item active">
        <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}" class="item-link">
            {{ page_obj.number }}</a>
    </li>

    {% if page_obj.has_next %}
    <li class="page-item">
      <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="item-link">
          {{ page_obj.next_page_number }}
      </a>
    </li>
    {% endif %}

    <li class="page-item">
      <a href="{% url 'core:MovieList' %}?page=last">Last</a>
    </li>
  </ul>
</div>
{% endif %} 

{% endblock main %} 

{% block sidebar %}
<p>Using https? {{ request.is_secure|yesno }}</p>
{% endblock sidebar %}

djangoapp/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.first_name }}
{{ object.last_name }}
{% endblock title %}

{% block main %}

<h1>{{ object }}</h1>
<h2>Actor</h2>
<ul>
    {% for role in object.role_set.all %}
        <li>
            <a href="{% url 'core:MovieDetail' role.movie.id}">{{ role.movie }}</a>:
            {{ role.name }}
        </li>
    {% endfor %}
</ul>

<h2>Writer</h2>
<ul>
    {% for movie in object.writing_credits.all %}
        <li>
            <a href="{% url 'core:MovieDetail' movie.id}">{{ movie }}</a>
        </li>
    {% endfor %}
</ul>

<h2>Director</h2>
<ul>
    {% for movie in object.directed.all %}
        <li>
            <a href="{% url 'core:MovieDetail' movie.id %}">{{ movie  }}</a>
        </li>
        
    {% endfor %}
</ul>
{% endblock main %}

djangoapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link href="{% static 'css/font-awesome.min.css' %}" rel='stylesheet'>
        <link href="{% static 'css/styles.css' %}" rel='stylesheet'>


        <title>{% block title %}Movie{% endblock title %}</title>
    </head>
    <body>


        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="#">MDB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="#"><i class="fa fa-home"></i>Home <span class="sr-only">(current)</span></a>
                {% if request.user.is_authenticated  %}
                    Hello, {{ request.user.first_name }}
              <a class="nav-item nav-link" href="{% url 'logout' %}">Log Out</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'login' %}">Log In</a>
                {% endif %}
            </div>
        </div>
    </nav>


        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        <a href="{% url "core:MovieList" %}">Movies</a>
                    </li>
                </ol>
            </nav>
        </div>

{%	if	messages	%}
	{%	for	message	in	messages	%}
        <div class="alert alert-{{ message.tags }} fade in">
			{{	message|safe	}}
		</div>
	{%	endfor	%}
{%	endif	%}


        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    {% block main %}
                    {% endblock main %}
                </div>
                <div class="col-sm-4">
                    {% block sidebar %} 
                    {% endblock sidebar %}
                </div>
            </div>
            
        </div>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

djangoapp/user/templates/user/dashboard.html
{% extends "base.html"	%}

{% block title %}
Dashboard
{%	endblock title %}

{% block main%}
<h1>Dashboard</h1>
<p>Welcome to your dashboard. You can <a	href="{% url	"edit" %}">edit your profile</a>	or <a href="{% url	"password_change" %}">change your password</a>.</p>
{% endblock main  %}

djangoapp/user/templates/user/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Edit profile
{% endblock title %}
{% block main %}
<div class="account-details-container">
    <p>You can edit your account using the following form:</p>
		<form action="." method="post" enctype="multipart/form-data">

           {% csrf_token %}
           {{ user_form|crispy }}
           {{ profile_form|crispy }}

           <button class="btn btn-primary">Save</button>
         </form>
     <div>
{% endblock %}

djangoapp/user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block main %}
      <div class="account-details-container">
        <h1>Signup</h1>
        <form action="{% url 'register' %}" method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-primary">Create</button>
        </form>
    </div>
    
{% endblock %}

djangoapp/user/templates/user/register_done.html
{%	extends	"base.html"	%}

{%	block	title	%}
Welcome to {{ block.super }}
{%	endblock	%}

{%	block main	%}
<div class='create-account-msg-container'>                  
    <div class='circle'>
        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
    </div>
    <h3>Your account have been successfully created!</h3>
    <a href="{% url 'login' %}">Click here to login</a>
</div>
{%	endblock main %}